#!/usr/bin/env python

data = ("John", "Doe", 53.44)
format_string = "Hello %s %s. Your current balance is %s$."

print format_string % data

data2 = ("miko", "jojo", "koko")

print "\n"

print "\t%s\t \t%s\t \t%s\t" % data2

print "\t:)\t \t\t:)\t \t\t:)\t"
